version: '1.0'

services:

  nginx:
    image: nginx:1.22
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./deployment/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/config/nginx/conf.d:/etc/nginx/conf.d
      - ./deployment/logs/nginx:/var/log/nginx
      - D:\stone\data:/data/static

  mysql:
    image: mysql:5.7
    container_name: mysql
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=stone
      - MYSQL_ROOT_PASSWORD=dyj123

  redis:
    image: redis:6.0.20
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  minio:
    image: bitnami/minio:2023
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - 'minio:/data'

#  mc:
#    image: minio/mc:latest
#    entrypoint: sleep
#    command: infinity

#  web:
##    build:
##      context: .
##      dockerfile: Dockerfile
#    image: stone:base
#    container_name: stone-web
#    ports:
#      - "0.0.0.0:32000:9900"
#      - "0.0.0.0:32001:9901"
#    depends_on:
#      - minio
#      - redis
#      - mysql
#      - nginx

volumes:
  nginx:
  mysql:
  redis:
  minio:
    driver: local
