version: '1.0'

services:

#  nginx:
#    image: nginx:1.22
#    container_name: nginx
#    ports:
#      - 80:80
#    volumes:
#      - ./deployment/config/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./deployment/config/nginx/conf.d:/etc/nginx/conf.d
#      - ./deployment/logs/nginx:/var/log/nginx
#      - D:\stone\data:/data/static
#    depends_on:
#      - stone-web
#
#  mysql:
#    image: mysql:5.7
#    container_name: mysql
#    ports:
#      - 3306:3306
#    volumes:
#      - mysql:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=dyj123
#
#  redis:
#    image: redis:6.0.20
#    container_name: redis
#    ports:
#      - 6379:6379
#    volumes:
#      - redis:/data
#
#  minio:
#    image: bitnami/minio:2023
#    container_name: minio
#    ports:
#      - 9000:9000
#      - 9001:9001
#    environment:
#      - MINIO_ROOT_USER=minioadmin
#      - MINIO_ROOT_PASSWORD=minioadmin
#    volumes:
#      - minio:/data
#
#  minio-mc:
#    image: minio/mc:latest
#    container_name: minio-mc
#    entrypoint: sleep
#    command: infinity

  stone-web:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: stone:web
    container_name: stone-web
    working_dir: /data/www/stone
    command: ['python', 'app.py']
    ports:
      - 6666:6666
    environment:
      - STONE_ENV=test
    volumes:
      - ./local_settings:/data/www/stone/local_settings
#    depends_on:
#      - minio
#      - redis
#      - mysql

volumes:
  nginx:
  mysql:
  redis:
  minio:
    driver: local
